version: '3'

services:

  web:
    image: nginx:1.15.0-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - node-network

  app:
    image: node:15
    container_name: nodejs
    tty: true
    working_dir: /usr/src/app
    command: sh -c "npm init -y && npm install express && npm install mysql && node index.js"
    expose:
      - "3000"
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
